services:
  product-service:
    build: ./product-services
    ports:
      - "${PRODUCT_SERVICE_PORT}:3000"
    env_file:
      - .env
    environment:
      DB_HOST: ${PRODUCT_DB_HOST}
      DB_NAME: ${PRODUCT_DB_NAME}
      DB_USER: ${PRODUCT_DB_USER}
      DB_PASSWORD: ${PRODUCT_DB_PASSWORD}
    container_name: product-services
    restart: always
    depends_on:
      - product-db

  product-db:
    image: mysql:8.0.36
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${PRODUCT_DB_PASSWORD}
      MYSQL_DATABASE: ${PRODUCT_DB_NAME}
    volumes:
      - product-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    container_name: phpmyadmin
    restart: always
    depends_on:
      - product-db
    environment:
      PMA_HOST: product-db
      PMA_PORT: 3306

  cart-service:
    build: ./cart-services
    container_name: cart-services
    ports:
      - "8000:8000"
    depends_on:
      - cart-db
    volumes:
      - ./cart-services:/var/www/html

  cart-db:
    image: mysql:8.0
    container_name: cart-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cartdb
    ports:
      - "3307:3306"
    volumes:
      - cart-db-data:/var/lib/mysql

  review-service:
    build: ./review-services
    ports:
      - "5002:5002"
    container_name: review-services
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
    environment:
      MONGO_URI: mongodb://admin:admin123@mongo-db:27017/reviewdb?authSource=admin

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INTIDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    env_file:
      - .env
    environment:
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db:27017/?authSource=admin
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    restart: always
    depends_on:
      - mongo-db

  user-service:
    build: ./user-services
    container_name: user-service
    ports:
      - "4000:4000"
    environment:
      DB_HOST: user-db
      DB_NAME: userdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      user-db:
        condition: service_healthy

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  product-db-data:
  mongo-data:
  user-db-data:
  cart-db-data: